### ISSUE TITLE
Variable name typo vs. the HyperSpec offline

### ISSUE THREAD

**Issue by gauthma** [kovisoft/slimv#28] opened 2015-05-09 11:11 UTC
In file `ftplugin/slimv.vim` there is a typo in lines 3175 and 3176: `g:slimv_hs_root` should be `g:slimv_clhs_root`. This causes an error message to be thrown when setting (in `.vimrc`) the latter variable: it complains that `g:slimv_hs_root` is unknown...

Simply correcting the name seems to have fixed the problem.

**Comment by kovisoft** [comment] 2015-05-10 16:51
No, this is not a typo. The hyperspec (api documentation) is defined per language, so `g:slimv_clhs_root` is defined/accessed for lisp in `slimv-lisp.vim` and `g:slimv_cljapi_root` is defined for clojure in `slimv-clojure.vim`. In the (mostly) language independent code `slimv.vim` there should be no language specific api definition accessed, it is handled by the language specific `SlimvHyperspecLookup()` function.

Actually `g:slimv_hs_root` is a leftover from earlier slimv versions and as I see currently it is used as a general hyperspec root for other languages.

Let's focus instead on the error message you got. Could you please tell me what was your exact variable definition and what error message you got?

**Comment by gauthma** [comment] 2015-05-11 09:14
This configuration in `~/.vim/ftplugin/lisp.vim` (it is the same thing if it is in `~/.vimrc`, or if I replace the ~ with the home folder):

~~~ text
let g:slimv_clhs_root="~/tmp/HyperSpec/Body/"
~~~

Causes this error in vim, when the cursor on top of a standard function/etc, and documentation is invoked:
~~~ text
Error detected while processing function SlimvHyperspec..SlimvLookup:
line   28:
E121: Undefined variable: g:slimv_hs_root
E116: Invalid arguments for function exists( g:slimv_hs_root )
E15: Invalid expression: match( symbol[1], ':' ) < 0 && exists( g:slimv_hs_root )
line   40:
E121: Undefined variable: page
E15: Invalid expression: '! ' . g:slimv_browser_cmd . ' ' . page . ' ' . g:slimv_browser_cmd_suffix
~~~

Removing the `let g:slimv_clhs_root` everything works properly, but the *online* spec is accessed (which is what I wanted to avoid).

**Comment by kovisoft** [comment] 2015-05-11 12:23
Ah, thanks, now I see what the problem is: `g:slimv_hs_root` is not enclosed in quotes.
Could you please check that you change this line (line 3175):
```
        if match( symbol[1], ':' ) < 0 && exists( g:slimv_hs_root )
```
to this:
```
        if match( symbol[1], ':' ) < 0 && exists( 'g:slimv_hs_root' )
```
and keep your `let g:slimv_clhs_root` settings in your `.vimrc`. Does it solve the problem?

**Comment by gauthma** [comment] 2015-05-11 17:31
Yes it did! Yay :D

On Mon, May 11, 2015 at 05:23:41am -0700, Tamas Kovacs wrote:
>Ah, thanks, now I see what the problem is: `g:slimv_hs_root` is not enclosed in quotes.
>Could you please check that you change this line (line 3175):
>```
>        if match( symbol[1], ':' ) < 0 && exists( g:slimv_hs_root )
>```
>to this:
>```
>        if match( symbol[1], ':' ) < 0 && exists( 'g:slimv_hs_root' )
>```
>and keep your `let g:slimv_clhs_root` settings in your `.vimrc`. Does it solve the problem?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kovisoft/slimv/issues/28#issuecomment-100890368


-- 
Óscar Pereira  |  https://erroneousthoughts.org
 
Rules of Optimisation:
Rule 1: Don't do it.
Rule 2 (for experts only): Don't do it yet.
                  -- M.A. Jackson

**Comment by kovisoft** [comment] 2015-05-11 19:12
OK, thanks for the test. I committed the fix in https://github.com/kovisoft/slimv/commit/97932fc1c4464b2fdfcecb894515d7e7bc9effbe

**Closed** 2015-05-16 15:28 UTC
